# Generated by Django 5.0.6 on 2024-06-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name": "Платежи", "verbose_name_plural": "Платежи"},
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
