# Generated by Django 5.0.6 on 2024-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_options_alter_payments_amount_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={},
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
