# Generated by Django 5.0.6 on 2024-06-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_options_alter_payments_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="date_paid",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="дата оплаты"
            ),
        ),
    ]
