# Generated by Django 5.0.6 on 2024-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на сессию"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount_paid",
            field=models.PositiveIntegerField(default=0, verbose_name="платеж"),
        ),
    ]
