# Generated by Django 5.0.6 on 2024-06-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payments_link_alter_payments_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="subs",
            field=models.BooleanField(default=False, verbose_name="подписка активна"),
        ),
    ]
