# Generated by Django 5.0.6 on 2024-06-22 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_subscriptions_subs"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="last_login",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
