# Generated by Django 5.0.6 on 2024-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_payments_last_login_user_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
